# ————— SERIAL CONFIGURATION —————
PORT = "COM4"       #serial port
BAUD = 9600
TIMEOUT = 1

# ————— VISUALIZATION SETTINGS —————
REFRESH_RATE = 60   #Hz
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 700

# ————— IMU BOX DIMENSIONS —————
BOX_LENGTH = 2
BOX_HEIGHT = 0.3
BOX_WIDTH = 1

# ————— PARTICLE SYSTEM SETTINGS —————
MAX_PARTICLES = 100
PARTICLE_LIFETIME = 60  #frames
PARTICLE_SIZE = 0.05
TRAIL_LENGTH = 50
TRAIL_LIFETIME = 200    #frames

# ————— DETECTION THRESHOLDS —————
SHAKE_THRESHOLD = 20    #degrees change for shake detection
SHAKE_COUNT_TRIGGER = 3 #consecutive rapid changes needed
EXTREME_TILT_THRESHOLD = 45  #degrees
MOVEMENT_THRESHOLD = 5  #degrees for trail creation
SIGNIFICANT_MOVEMENT = 10  #degrees for random effects

# ————— AUDIO SETTINGS —————
BEEP_FREQUENCY = 800
BEEP_DURATION = 0.1
MODE_CHANGE_BEEP = 1000
EXTREME_TILT_BEEP = 2000
SHAKE_BEEP = 1500